dist: xenial
language: python
python:
  - "3.6"
branches:
  except:
    - master
install:
  - pip install -r requirements.txt
script:
  - echo "this would be where I run pytest..."
before_deploy:
  - ./can_publish.sh
  - pelican content
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: output
    target-branch: master
    keep_history: true
    verbose: true
    on:
      branch: src
