dist: xenial
language: python
python:
  - "3.6"
branches:
  only:
    - src
install:
  - pip install -r requirements.txt
script:
  - echo "hello world"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: output
  target-branch: master
  keep_history: true
  verbose: true